# Generated by Django 5.2.3 on 2025-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/product_videos/'),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='image',
            field=models.ImageField(upload_to='images/bundles/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/product_images/'),
        ),
    ]
