# Generated by Django 5.2.3 on 2025-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_productimage_order_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
