# Generated by Django 5.2.3 on 2025-06-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='images/product_images/'),
        ),
    ]
