# Generated by Django 5.2.3 on 2025-06-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Camera drone', 'Drone con cámara'), ('Portable', 'Producto portátil'), ('Energy', 'Energía'), ('Accessory', 'Accesorio')], max_length=50, unique=True)),
                ('series', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Product Series',
                'verbose_name_plural': 'Product Series',
            },
        ),
    ]
