# Generated by Django 5.2.3 on 2025-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productseries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSeries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL embebible de YouTube/Vimeo', max_length=500, null=True),
        ),
    ]
