# Generated by Django 5.2.3 on 2025-06-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_productseries_remove_product_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video_url',
            new_name='video',
        ),
    ]
