# Generated by Django 5.2.3 on 2025-06-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_video_url_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procuct_details',
            field=models.TextField(blank=True),
        ),
    ]
