# Generated by Django 5.2.3 on 2025-06-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_slogan_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel_image',
            field=models.ImageField(blank=True, upload_to='images/product_images/'),
        ),
    ]
